# -*- coding: utf-8 -*-
"""python_basics.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YsPwHaEC9z-Pddq95yH4Zbd4O50sijms
"""

print("hello")

